public enum GameState
{
    TITLE_MENU,
    MAIN_MENU,
    SHOP_MENU,
    GEARS_MENU,
    SCORES_MENU,
    LOADING,
    RUNNING,
    PAUSED,
    UNPAUSED,
    RELOADING,
    QUITTING,
    FAIL_MENU,
    VICTORY_MENU,
    STATS_MENU,
    REGISTER_MENU
}